GET https://api-937n.onrender.com/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "securepassword123",
    "role": "alumno"
}

###
GET https://api-937n.onrender.com/api/tfgs

###
GET http://localhost:3000/api/tfgs

###
GET http://localhost:3000/api/tfgs/67bdc66d8feab4c55cc21e6c

###
PATCH http://localhost:3000/api/tfgs/67bdc66d8feab4c55cc21e6c
Content-Type: application/json

{
    "Titulación de Grado": "TFG de prueba",
    "Tutor": "Federica Peinado",
    "Alumno": "Tu madre y tu padre"
}

# DELETE, CREATE
